hmsprj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('room/', include('room.urls')),
]

room/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add-category/', views.add_category, name='add-category'),
    path('update-category/<int:pk>/', views.update_category, name='update-category'),
    path('delete-category/<int:pk>/', views.delete_category, name='delete-category'),

    path('add-room/', views.add_room, name='add-room'),
    path('update-room/<int:pk>/', views.update_room, name='update-room'),
    path('all-rooms/', views.all_rooms, name='all-rooms'),
    path('delete-room/<int:pk>/', views.delete_room, name='delete-room'), 

    path('new-booking/<int:pk>/', views.new_booking, name='new-booking'),
    path('update-booking/<int:pk>/', views.update_booking, name='update-booking'),

    path('checkout-guest/<int:pk>/', views.checkout_guests, name='checkout-guest'),


    path('guest-history-per-room/<int:pk>/', views.guest_history_per_room, name='guest-history-per-room'),
    path('all-active-guests/', views.all_active_guests, name='all-active-guests'),
]

room/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Category(models.Model):
    name = models.CharField(max_length=100)
    amount = models.PositiveIntegerField()

    def __str__(self):
        return self.name

class Room(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100)
    is_available = models.BooleanField(default=True)

class Booking(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    guest_name = models.CharField(max_length=100)
    guest_email = models.EmailField(max_length=100)
    guest_phone = models.CharField(max_length=20)
    start_date = models.DateField()
    end_date = models.DateField()
    timestamp = models.DateTimeField(auto_now_add=True)
    checkedout = models.BooleanField(default=False)

room/forms.py
from django import forms
from . import models

class AddCategoryForm(forms.ModelForm):
    class Meta:
        model = models.Category
        fields = ['name', 'amount']

class UpdateCategoryForm(forms.ModelForm):
    class Meta:
        model = models.Category
        fields = ['name', 'amount']

class AddRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = ['category', 'name']

class UpdateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = ['category', 'name']

class NewBookingForm(forms.ModelForm):
    class Meta:
        model = models.Booking
        exclude = ('room', 'timestamp',)

class UpdateBookingForm(forms.ModelForm):
    class Meta:
        model = models.Booking
        exclude = ('room', 'timestamp',)

room/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from . forms import *
from . models import *

def add_category(request):
    category = Category.objects.all()
    if request.method == 'POST':
        form = AddCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "New category added to manage rooms ")
            return redirect('add-category')
        else:
            messages.warning(request, "Something went wrong. please check for inputs")
            return redirect('add-category')
    else:
        form = AddCategoryForm()
        context = {'form':form, 'category':category}
    return render(request, 'room/add-category.html', context)

def update_category(request, pk):
    category = Category.objects.get(pk=pk)
    categories = Category.objects.all()
    if request.method == 'POST':
        form = UpdateCategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, "Category information updated and saved")
            return redirect(reverse('update-category', args=[category.pk]))
        else:
            messages.warning(request, "Somethin went wrong. please check for errors")
            return redirect(reverse('update-category', args=[category.pk]))
    else:
        form = UpdateCategoryForm(instance=category)
        context = {'form':form, 'category':category, 'categories':categories}
    return render(request, 'room/update-category.html', context)

def delete_category(request, pk):
    category = Category.objects.get(pk=pk)
    category.delete()
    messages.success(request, "Category is now deleted")
    return redirect('dashboard')
            
def add_room(request):
    room = Room.objects.all()[:5]
    if request.method == 'POST':
        form = AddRoomForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "New room information added and saved")
            return redirect('add-room')
        else:
            messages.warning(request, "Somethin went wrong. please check for errors")
            return redirect('add-room')
    else:
        form = AddRoomForm()
        context = {'form':form, 'room':room}
    return render(request, 'room/add-room.html', context)

def update_room(request, pk):
    rooms = Room.objects.get(pk=pk)
    room = Room.objects.all()
    if request.method == 'POST':
        form = UpdateRoomForm(request.POST, instance=rooms)
        if form.is_valid():
            form.save()
            messages.success(request, "Form info is now updated and saved")
            return redirect(reverse('update-room', args=[rooms.pk]))
        else:
            messages.warning(request, "Somethin went wrong. please check for errors")
            return redirect(reverse('update-room', args=[rooms.pk]))
    else:
        form = UpdateRoomForm(instance=rooms)
        context = {'form':form, 'rooms':rooms, 'room':room}
    return render(request, 'room/update-room.html', context)

def all_rooms(request):
    rooms = Room.objects.all()
    context = {'rooms':rooms}
    return render(request, 'room/all-rooms.html', context)

def delete_room(request, pk):
    room = Room.objects.get(pk=pk)
    room.delete()
    messages.success(request, "Room has been deleted")
    return redirect('all-rooms')

def new_booking(request, pk):
    room = Room.objects.get(pk=pk)
    if request.method == 'POST':
        form = NewBookingForm(request.POST)
        if form.is_valid():
            var = form.save(commit=False)
            var.room = room
            room.is_available = False
            var.save()
            room.save()
            messages.success(request, 'New booking has been made')
            return redirect('dashboard')
        else:
            messages.warning(request, 'Something went wrong. please check')
            return redirect(reverse('new-booking', args=[room.pk]))
    else:
        form = NewBookingForm()
        context = {'room':room, 'form':form}
    return render(request, 'room/new-booking.html', context)

def update_booking(request, pk):
    booking = Booking.objects.get(pk=pk)
    if request.method == 'POST':
        form = UpdateBookingForm(request.POST, instance=booking)
        if form.is_valid():
            form.save()
            messages.success(request, 'Booking info has been updated and save')
            return redirect(reverse('update-booking', args=[booking.pk]))
        else:
            messages.warning(request, 'Something went wrong. please check')
            return redirect(reverse('update-booking', args=[booking.pk]))
    else:
        form = UpdateBookingForm(instance=booking)
        context = {'form':form, 'booking':booking}
    return render(request, 'room/update-booking.html', context)

def checkout_guests(request, pk):
    booking = Booking.objects.get(pk=pk)
    booking.checkedout = True

    room = Room.objects.get(pk=booking.room.pk)
    room.is_available = True
    room.save()
    booking.save()
    messages.success(request, 'Guest has been checked out and room is now available for use..')
    return redirect('dashboard')

def guest_history_per_room(request, pk):
    room = Room.objects.get(pk=pk)
    guest = room.booking_set.all().order_by('checkedout')
    context = {'guest':guest, 'room':room}
    return render(request, 'room/guest-history-per-room.html', context)

def all_active_guests(request):
    guests = Booking.objects.filter(checkedout=False)
    context = {'guests':guests}
    return render(request, 'room/all-active-guests.html', context)

templates/room/add-category.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load humanize %}

{% block content %}

<div class="row justify-content-center">
  <div class="col-md-8">
    <div class="content-container">
      <h2 class="text-center mb-4">Add Category</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-floating mb-3">
          {% render_field form.name class="form-control" %}
          <label for="floatingInput">Name</label>
        </div>
        <div class="form-floating mb-3">
          {% render_field form.amount class="form-control" %}
          <label for="floatingInput">Amount</label>
        </div>
        <button type="submit" class="btn btn-primary w-100">Submit</button>
      </form>
    </div>
  </div>
</div>

<div class="row justify-content-center mt-5">
  <div class="col-md-12">
    <div class="content-container">
      <h2 class="text-center mb-4">Category List</h2>
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <thead class="table-light">
            <tr class="text-center">
              <th scope="col">Name</th>
              <th scope="col">Amount</th>
              <th scope="col">Rooms (Total)</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for cat in category %}
            <tr class="text-center">
              <td>{{ cat.name }}</td>
              <td><small class="text-muted">LKR</small> {{ cat.amount | intcomma }}</td>
              <td>{{ cat.room_set.all.count }}</td>
              <td>
                <a href="{% url 'update-category' cat.pk%}" class="btn btn-primary btn-sm"> <i class="fa fa-pencil"></i> </a>
                <a href="#" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal{{ cat.pk }}"><i class="fa fa-trash"></i> </a>
            </td>

            <div class="modal fade" id="deleteModal{{ cat.pk }}" tabindex="-1" aria-labelledby="deleteModalLabel{{ cat.pk }}" aria-hidden="true">
              <div class="modal-dialog">
              <div class="modal-content">
                  <div class="modal-header">
                  <h5 class="modal-title" id="deleteModalLabel{{ cat.pk }}">>Delete {{cat.name}}</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                      Deleting this category would also permanently delete all rooms that is associated with this category.
                  </div>
                  <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <a href="{% url 'delete-category' cat.pk %}" type="button" class="btn btn-danger">Delete</a>
                  </div>
              </div>
              </div>
          </div>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/room/add-room.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="content-container">
        <h2 class="text-center mb-4">Add Room</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-floating mb-3">
            {% render_field form.category class="form-control" %}
            <label for="floatingInput">Category</label>
            </div>
            <div class="form-floating mb-3">
            {% render_field form.name class="form-control" %}
            <label for="floatingInput">Room name</label>
            </div>
            <button type="submit" class="btn btn-primary w-100">Submit</button>
        </form>
        </div>
    </div>
</div>

<div class="row justify-content-center mt-5">
    <div class="col-md-12">
      <div class="content-container">
        <h2 class="text-center mb-4">Room List</h2>
        <div class="table-responsive">
          <table class="table table-bordered table-hover">
            <thead class="table-light">
              <tr class="text-center">
                <th scope="col">Category</th>
                <th scope="col">Name</th>
                <th scope="col">Status</th>
                <th scope="col">Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for r in room %}
              <tr class="text-center">
                <td>{{r.category}}</td>
                <td>{{r.name}}</td>
                {% if r.is_available %}
                <td><span class="badge bg-primary">Available</span></td>
                {% else %}
                <td><span class="badge bg-warning">Occupied</span></td>
                {% endif %}
                <td>
                    <a href="{% url 'update-room' r.pk%}" class="btn btn-primary btn-sm"> <i class="fa fa-pencil"></i> </a>
                    <a href="#" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal{{ r.pk }}"> <i class="fa fa-trash"></i> </a>
                </td>

                <div class="modal fade" id="deleteModal{{ r.pk }}" tabindex="-1" aria-labelledby="deleteModalLabel{{ r.pk }}" aria-hidden="true">
                    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel{{ r.pk }}">Delete {{r.name}}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Deleting this room would also permanently delete all booking that is associated with this room.
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <a href="{% url 'delete-room' r.pk %}" type="button" class="btn btn-danger">Delete</a>
                        </div>
                    </div>
                    </div>
                </div>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>

{% endblock content %}

templates/room/all-active-guests.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center mt-5">
    <div class="col-md-12">
      <div class="content-container">
        <h2 class="text-center mb-4">All Active Guests</h2>
        <div class="table-responsive">
          <table class="table table-bordered table-hover">
            <thead class="table-light">
              <tr class="text-center">
                <th scope="col">Guest Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Room</th>
                <th scope="col">Start Date</th>
                <th scope="col">End Date</th>
                <th scope="col">Update</th>
                <th scope="col">Checkout</th>
              </tr>
            </thead>
            <tbody>
              {% for g in guests %}
              <tr class="text-center">
                <td>{{g.guest_name}}</td>
                <td>{{g.guest_email}}</td>
                <td>{{g.guest_phone}}</td>
                <td>{{g.room.name}}</td>
                <td>{{g.start_date}}</td>
                <td>{{g.end_date}}</td>

                <td>
                    <a href="{% url 'update-booking' g.pk %}" class="btn btn-warning btn-sm"><i class="fa fa-pencil"></i></a>
                </td>
                <td>
                    <a href="{% url 'checkout-guest' g.pk %}" class="btn btn-primary btn-sm">Checkout Guest</a>
                </td>
                
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>

{% endblock content %}

templates/room/all-rooms.html
{% extends 'base.html' %}

{% block content %}

<div class="row justify-content-center mt-5">
    <div class="col-md-12">
      <div class="content-container">
        <h2 class="text-center mb-4">All Rooms</h2>
        <div class="table-responsive">
          <table class="table table-bordered table-hover">
            <thead class="table-light">
              <tr class="text-center">
                <th scope="col">Categroy</th>
                <th scope="col">Name</th>
                <th scope="col">Status</th>
                <th scope="col">Booking</th>
                <th scope="col">Guest History</th>
                <th scope="col">Actions</th>
                <th scope="col">Info</th>
              </tr>
            </thead>
            <tbody>
              {% for r in rooms %}
              <tr class="text-center">
                <td>{{r.category}}</td>
                <td>{{r.name}}</td>
                {% if r.is_available %}
                <td><span class="badge bg-primary">Available</span></td>
                {% else %}
                <td><span class="badge bg-warning">Occupied</span></td>
                {% endif %}

                {% if r.is_available %}
                <td><a href="{% url 'new-booking' r.pk%}" class="btn btn-outline-primary btn-sm">Book Room</a></td>
                {% else %}
                <td><a href="{% url 'checkout-guest' r.booking_set.all.last.pk %}" class="btn btn-outline-warning btn-sm">Checkout Guest</a></td>
                {% endif %}

                <td><a href="{% url 'guest-history-per-room' r.pk%}" class="btn btn-primary btn-sm">View History</a></td>

                <td>
                    <a href="{% url 'update-room' r.pk%}" class="btn btn-primary btn-sm"> <i class="fa fa-pencil"></i> </a>
                    <a href="#" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal{{ r.pk }}"> <i class="fa fa-trash"></i> </a>
                </td>

                <div class="modal fade" id="deleteModal{{ r.pk }}" tabindex="-1" aria-labelledby="deleteModalLabel{{ r.pk }}" aria-hidden="true">
                  <div class="modal-dialog">
                  <div class="modal-content">
                      <div class="modal-header">
                      <h5 class="modal-title" id="deleteModalLabel{{ r.pk }}">Delete {{r.name}}</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                          Deleting this room would also permanently delete all booking that is associated with this room.
                      </div>
                      <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      <a href="{% url 'delete-room' r.pk %}" type="button" class="btn btn-danger">Delete</a>
                      </div>
                  </div>
                  </div>
              </div>

                <td>
                    {% if not r.is_available %}
                    Occupied until {{r.booking_set.all.last.end_date}}
                    {% else %}
                    --
                    {% endif %}
                </td>
                
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>


{% endblock content %}

templates/room/guest-history-per-room.html
{% extends 'base.html' %}

{% block content %}

<div class="row justify-content-center mt-5">
    <div class="col-md-12">
      <div class="content-container">
        <h2 class="text-center mb-4">Guest History in {{room.name}}</h2>
        <div class="table-responsive">
          <table class="table table-bordered table-hover">
            <thead class="table-light">
              <tr class="text-center">
                <th scope="col">Guest Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Room</th>
                <th scope="col">Start Date</th>
                <th scope="col">End Date</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
                {% for g in guest %}
                <tr class="text-center">
                    <td>{{g.guest_name}}</td>
                    <td>{{g.guest_email}}</td>
                    <td>{{g.guest_phone}}</td>
                    <td>{{g.room.name}}</td>
                    <td>{{g.start_date}}</td>
                    <td>{{g.end_date}}</td>
                    <td>
                        {% if g.checkedout %}
                        <span class="badge bg-warning">Checked Out</span>
                        {% else %}
                        <span class="badge bg-success">Occupied</span>
                        {% endif %}
                    </td>
                    
                </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/room/new-booking.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="row justify-content-center">
  <div class="col-md-8">
    <div class="content-container">
      <h2 class="text-center mb-4">Book a Room</h2>
      <form class="p-4 p-md-5 border rounded-3 bg-light" method="post">
        {% csrf_token %}
        <div class="form-floating mb-3">
          <input type="text" name="username" value="{{ room.name }}" class="form-control" id="floatingRoom" disabled>
          <label for="floatingRoom">Room</label>
        </div>
        <div class="form-floating mb-3">
          {% render_field form.guest_name class="form-control" %}
          <label for="floatingGuestName">Guest Fullname</label>
        </div>
        <div class="form-floating mb-3">
          {% render_field form.guest_email class="form-control" %}
          <label for="floatingGuestEmail">Guest Email</label>
        </div>
        <div class="form-floating mb-3">
          {% render_field form.guest_phone class="form-control" %}
          <label for="floatingGuestPhone">Phone Number</label>
        </div>
        <div class="form-floating mb-3">
          {% render_field form.start_date type='date' class="form-control" %}
          <label for="floatingStartDate">Start Date</label>
        </div>
        <div class="form-floating mb-3">
          {% render_field form.end_date type='date' class="form-control" %}
          <label for="floatingEndDate">End Date</label>
        </div>
        <button class="w-100 btn btn-primary btn-lg" type="submit">Submit</button>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

templates/room/update-booking.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-md-8">
      <div class="content-container">
        <h2 class="text-center mb-4">Book a Room</h2>
        <form class="p-4 p-md-5 border rounded-3 bg-light" method="post">
          {% csrf_token %}
          <div class="form-floating mb-3">
            <input type="text" name="username" value="{{ booking.room.name }}" class="form-control" id="floatingRoom" disabled>
            <label for="floatingRoom">Room</label>
          </div>
          <div class="form-floating mb-3">
            {% render_field form.guest_name class="form-control" %}
            <label for="floatingGuestName">Guest Fullname</label>
          </div>
          <div class="form-floating mb-3">
            {% render_field form.guest_email class="form-control" %}
            <label for="floatingGuestEmail">Guest Email</label>
          </div>
          <div class="form-floating mb-3">
            {% render_field form.guest_phone class="form-control" %}
            <label for="floatingGuestPhone">Phone Number</label>
          </div>
          <div class="form-floating mb-3">
            {% render_field form.start_date type='date' class="form-control" %}
            <label for="floatingStartDate">Start Date</label>
          </div>
          <div class="form-floating mb-3">
            {% render_field form.end_date type='date' class="form-control" %}
            <label for="floatingEndDate">End Date</label>
          </div>
          <button class="w-100 btn btn-primary btn-lg" type="submit">Submit</button>
        </form>
      </div>
    </div>
  </div>


{% endblock content %}

templates/room/update-category.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="content-container">
            <h2 class="text-center mb-4">Update Category</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    {% render_field form.name class="form-control" %}
                    <label for="floatingInput">Name</label>
                </div>
                <div class="form-floating mb-3">
                    {% render_field form.amount class="form-control" %}
                    <label for="floatingInput">Amount</label>
                </div>
                <button type="submit" class="btn btn-primary w-100">Submit</button>
            </form>
        </div>
    </div>
</div>

<div class="row justify-content-center mt-5">
    <div class="col-md-12">
      <div class="content-container">
        <h2 class="text-center mb-4">Category List</h2>
        <div class="table-responsive">
          <table class="table table-bordered table-hover">
            <thead class="table-light">
              <tr class="text-center">
                <th scope="col">Name</th>
                <th scope="col">Amount</th>
                <th scope="col">Rooms (Total)</th>
              </tr>
            </thead>
            <tbody>
                {% for cat in categories %}
                <tr class="text-center">
                    <td>{{cat.name}}</td>
                    <td>{{cat.amount}}</td>
                    <td>{{cat.room_set.all.count}}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>


{% endblock content %}

templates/room/update-room.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="content-container">
            <h2 class="text-center mb-4">Update Room</h2>
            <form method="post">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    {% render_field form.category class="form-control" %}
                    <label for="floatingInput">Category</label>
                </div>
                <div class="form-floating mb-3">
                    {% render_field form.name class="form-control" %}
                    <label for="floatingInput">Room name</label>
                </div>
                <button type="submit" class="btn btn-primary w-100">Submit</button>
            </form>
        </div>
    </div>
</div>

<div class="row justify-content-center mt-5">
    <div class="col-md-12">
      <div class="content-container">
        <h2 class="text-center mb-4">Room List</h2>
        <div class="table-responsive">
          <table class="table table-bordered table-hover">
            <thead class="table-light">
              <tr class="text-center">
                <th scope="col">Categroy</th>
                <th scope="col">Name</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
              {% for r in room %}
              <tr class="text-center">
                <td>{{r.category}}</td>
                <td>{{r.name}}</td>
                {% if r.is_available %}
                <td><span class="badge bg-primary">Available</span></td>
                {% else %}
                <td><span class="badge bg-warning">Occupied</span></td>
                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>


{% endblock content %}